name = "MathlibStats"
version = "0.1.0"
keywords = ["math"]
reservoir = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.26.0-rc2"

[[require]]
name = "lean_scout"
git = "https://github.com/mathlib-initiative/lean_scout.git"
rev = "v4.26.0-rc2"